import { NavLinkWithSubLinks } from './types';
import {
  Home, Briefcase, Cpu, Building2, Info, Library, Mail, Layers, Lightbulb, Handshake, Shield, Gavel, Users, Wifi, CreditCard, Tv2, MailCheck, ShieldCheck, Globe,
  Megaphone, CircleDollarSign, CalendarDays, Store, Puzzle, Link2, BarChart, Plane, FerrisWheel, HeartHandshake, Hotel, ConciergeBell, Landmark, ShoppingCart,
  ShoppingBag, Drama, BuildingIcon, School, MapPin, TrainFront, BookOpen, FileText, Wrench, HelpCircle, TrendingUp, Server, Bot, DatabaseZap, GraduationCap,
  MessageSquare, UsersCog
} from './components/Icons';

export const MAIN_NAV_LINKS: NavLinkWithSubLinks[] = [
  { href: '/', label: 'Home', icon: Home },
  {
    label: 'Products',
    href: '/products',
    basePath: '/products',
    icon: Layers,
    subLinks: [
      {
        href: '/products/intelligent-wifi',
        label: 'Intelligent Venue WiFi',
        icon: Wifi,
        shortDescription: 'The core connectivity platform, powered by Purple.',
        category: 'Core Platforms',
      },
      {
        href: '/products/all-axxess',
        label: 'All Axxess',
        icon: CreditCard,
        shortDescription: 'Comprehensive event management and cashless solutions.',
        category: 'Core Platforms',
      },
      {
        href: '/products/everlytic',
        label: 'Everlytic',
        icon: MailCheck,
        shortDescription: 'High-volume bulk messaging and marketing automation.',
        category: 'Core Platforms',
      },
      {
        href: '/products/cnntap',
        label: 'CNNTAP',
        icon: Tv2,
        shortDescription: 'Premium advertising platform via CNN Travel.',
        category: 'Core Platforms',
      },
      {
        href: '/products/friendly-wifi',
        label: 'Friendly WiFi',
        icon: ShieldCheck,
        shortDescription: 'Globally recognized certification for safe browsing.',
        category: 'Services & Add-Ons',
      },
      {
        href: '/products/internet-connectivity',
        label: 'Internet Connectivity',
        icon: Globe,
        shortDescription: 'Reliable, high-speed data connectivity solutions.',
        category: 'Services & Add-Ons',
      },
       {
        href: '/solutions/digital-marketing',
        label: 'Professional Services',
        icon: UsersCog,
        shortDescription: 'Expert strategy, custom integrations, and managed services.',
        category: 'Services & Add-Ons',
      },
    ],
  },
  {
    label: 'Solutions',
    href: '/solutions',
    basePath: '/solutions',
    icon: Lightbulb,
    subLinks: [
      {
        href: '/solutions/ai-gateway',
        label: 'Flow AI Gateway',
        icon: Cpu,
        shortDescription: 'The future of intelligent, automated venues.',
        category: 'AI & Automation',
      },
      {
        href: '/solutions/ai-integrations',
        label: 'AI Integrations',
        icon: Puzzle,
        shortDescription: 'Specialized services to connect all your systems.',
        category: 'AI & Automation',
      },
      {
        href: '/solutions/wifi-monetisation',
        label: 'WiFi Monetisation',
        icon: CircleDollarSign,
        shortDescription: 'Generate new revenue streams from your network.',
        category: 'Business Growth',
      },
      {
        href: '/solutions/sponsored-wifi',
        label: 'Sponsored WiFi',
        icon: Handshake,
        shortDescription: 'Partner-funded connectivity for your customers.',
        category: 'Business Growth',
      },
      {
        href: '/solutions/wifi-marketing',
        label: 'WiFi Marketing',
        icon: Megaphone,
        shortDescription: 'Engage visitors directly through the captive portal.',
        category: 'Business Growth',
      },
       {
        href: '/solutions/smb-wifi',
        label: 'SMB WiFi',
        icon: Store,
        shortDescription: 'Powerful, affordable solutions for small businesses.',
        category: 'Business Growth',
      },
      {
        href: '/solutions/event-wifi',
        label: 'Event WiFi',
        icon: CalendarDays,
        shortDescription: 'High-density solutions for seamless event connectivity.',
        category: 'Venue Solutions',
      },
      {
        href: '/solutions/3rd-party-integrations',
        label: '3rd Party Integrations',
        icon: Link2,
        shortDescription: 'Connect your existing tools with Purple Connectors.',
        category: 'Venue Solutions',
      },
      {
        href: '/solutions/digital-marketing',
        label: 'Digital Marketing',
        icon: BarChart,
        shortDescription: 'Professional services to promote your venue online.',
        category: 'Venue Solutions',
      },
    ],
  },
  {
    label: 'Industries',
    href: '/industries',
    basePath: '/industries',
    icon: Building2,
    subLinks: [
      { href: '/industries/airports', label: 'Airports', icon: Plane, category: 'Travel & Public Venues' },
      { href: '/industries/attractions', label: 'Attractions', icon: FerrisWheel, category: 'Hospitality & Leisure' },
      { href: '/industries/healthcare', label: 'Healthcare', icon: HeartHandshake, category: 'Hospitality & Leisure' },
      { href: '/industries/hotels', label: 'Hotels', icon: Hotel, category: 'Hospitality & Leisure' },
      { href: '/industries/hospitality', label: 'Hospitality', icon: ConciergeBell, category: 'Hospitality & Leisure' },
      { href: '/industries/museums', label: 'Museums', icon: Landmark, category: 'Hospitality & Leisure' },
      { href: '/industries/retail', label: 'Retail', icon: ShoppingCart, category: 'Commerce & Corporate' },
      { href: '/industries/shopping-malls', label: 'Shopping Malls', icon: ShoppingBag, category: 'Commerce & Corporate' },
      { href: '/industries/stadiums', label: 'Stadiums', icon: Drama, category: 'Travel & Public Venues' },
      { href: '/industries/offices', label: 'Offices', icon: BuildingIcon, category: 'Commerce & Corporate' },
      { href: '/industries/education', label: 'Schools & Campuses', icon: School, category: 'Commerce & Corporate' },
      { href: '/industries/towns-cities', label: 'Towns & Cities', icon: MapPin, category: 'Travel & Public Venues' },
      { href: '/industries/public-transport', label: 'Public Transport', icon: TrainFront, category: 'Travel & Public Venues' },
    ],
  },
  {
    label: 'Partners',
    href: '/partners',
    basePath: '/partners',
    icon: Handshake,
    subLinks: [
        { href: '/partners/technology', label: 'Technology Partners', icon: Cpu, shortDescription: 'The core tech powering Flow.', category: 'Our Ecosystem' },
        { href: '/partners/program', label: 'Partner Program', icon: Users, shortDescription: 'Join our reseller, agent, or affiliate programs.', category: 'Our Ecosystem' },
    ],
  },
  {
    label: 'Resources',
    href: '/resources',
    basePath: '/resources',
    icon: Library,
    subLinks: [
      { href: '/resources/case-studies', label: 'Case Studies', icon: BookOpen, shortDescription: 'Real-world success stories.', category: 'Knowledge Base' },
      { href: '/resources/guides-articles', label: 'Guides & Articles', icon: FileText, shortDescription: 'In-depth analysis and insights.', category: 'Knowledge Base' },
      { href: '/resources/tools', label: 'Tools', icon: Wrench, shortDescription: 'Calculators, estimators, and checklists.', category: 'Utilities' },
    ],
  },
  {
    label: 'Company',
    href: '/company',
    basePath: '/company',
    icon: Info,
    subLinks: [
      { href: '/company/about-us', label: 'About Us', icon: Users, category: 'Corporate' },
      { href: '/company/integrations', label: 'Integrations', icon: Puzzle, category: 'Corporate' },
      { href: '/company/blog', label: 'Blog', icon: MessageSquare, category: 'Corporate' },
      { href: '/company/legal', label: 'Legal', icon: Gavel, category: 'Legal' },
      { href: '/company/privacy-policy', label: 'Privacy Policy', icon: Shield, category: 'Legal' },
      { href: '/company/terms-of-use', label: 'Terms of Use', icon: Gavel, category: 'Legal' },
      { href: '/company/cookie-policy', label: 'Cookie Policy', icon: Gavel, category: 'Legal' },
      { href: '/company/sla', label: 'Standard SLA', icon: FileText, category: 'Legal' },
    ],
  },
  {
      label: 'Links',
      href: '/support',
      basePath: '/support',
      icon: HelpCircle,
      subLinks: [
          { href: 'https://support.purple.ai', label: 'Purple Support', icon: HelpCircle, category: 'Support'},
          { href: '/support/whatsapp', label: 'WhatsApp Support', icon: Bot, category: 'Support'},
          { href: '/contact', label: 'Contact Us', icon: Mail, category: 'Support'},
          { href: 'https://purpleportal.net', label: 'Purple Portal', icon: Server, category: 'Portals'},
          { href: '/support/my-data-portal', label: 'My Data Portal', icon: DatabaseZap, category: 'Portals'},
          { href: '/support/partner-portal', label: 'Partner Portal', icon: Handshake, category: 'Portals'},
      ]
  }
];
